# Generated by Django 5.1 on 2024-08-29 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meduser',
            name='title',
            field=models.CharField(choices=[('Dr', 'Doctor'), ('Nrs', 'Nurse'), ('Lab tech', 'Laboratory technician'), ('MD', 'Medical Director'), ('Admin', 'Administrator'), ('Pharm', 'Pharmacist')], default='', max_length=8, null=True),
        ),
    ]
