# Generated by Django 5.1 on 2024-09-16 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_patient_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='blood_sign',
            field=models.CharField(choices=[('POSITIVE', 'positive'), ('NEGATIVE', 'negative')], default='+', max_length=10),
        ),
        migrations.AddField(
            model_name='patient',
            name='height_unit',
            field=models.CharField(choices=[('M', 'Metre'), ('CM', 'Centimetre'), ('FT', 'Feet')], default='cm', max_length=10),
        ),
        migrations.AddField(
            model_name='patient',
            name='weight_unit',
            field=models.CharField(choices=[('KG', 'Kilogramme'), ('LBS', 'Pounds')], default='Kg', max_length=10),
        ),
    ]
