# Generated by Django 5.1 on 2024-09-02 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_employees_login_patient_signup_delete_medemployees'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
