# Generated by Django 5.1 on 2024-09-22 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_temporarytoken_delete_signup_employees_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporarytoken',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.employees'),
        ),
    ]
