# Generated by Django 5.1 on 2024-09-08 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_userprofile_user_remove_employees_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employees',
            old_name='users',
            new_name='user',
        ),
    ]
