# Generated by Django 5.1 on 2024-09-08 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_rename_users_employees_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='id',
        ),
        migrations.AlterField(
            model_name='patient',
            name='medical_record_number',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
