# Generated by Django 5.1 on 2024-09-08 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_remove_patient_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medication',
            name='dosage',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='employees',
        ),
        migrations.AddField(
            model_name='medication',
            name='type',
            field=models.CharField(choices=[('Brand', 'Brand Name'), ('Generic', 'Generic Name')], default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prescription',
            name='dosage',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medication',
            name='name',
            field=models.TextField(max_length=100),
        ),
    ]
