# Generated by Django 5.1 on 2024-09-12 08:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DepartmentName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('type', models.CharField(choices=[('Brand', 'Brand Name'), ('Generic', 'Generic Name')], max_length=50)),
                ('quantity_in_stock', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('username', models.CharField(blank=True, max_length=191, null=True)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('O', 'Other')], max_length=10)),
                ('address', models.TextField()),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('patient_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('date_registered', models.DateTimeField(auto_now_add=True)),
                ('changed_at', models.DateTimeField(auto_now=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('blood_type', models.CharField(blank=True, max_length=10, null=True)),
                ('genotype', models.CharField(blank=True, max_length=10, null=True)),
                ('folder', models.CharField(editable=False, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmployeeName', models.CharField(max_length=100)),
                ('DateEmployed', models.DateField()),
                ('Employees_Title', models.CharField(choices=[('DR', 'Doctor'), ('RN', 'Registered Nurse'), ('LT', 'Laboratory technician'), ('PH', 'Pharmacist'), ('CT', 'Consultant'), ('MD', 'Medical Director'), ('OB-GYN', 'Obstetrician and Gynaecologist'), ('Admin', 'Admin'), ('Recept', 'Receptionist'), ('CS', 'Clinical Staff'), ('OT', 'Other Staff')], default='DR', max_length=15)),
                ('Department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_profile', to='myapp.departments')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField()),
                ('status', models.CharField(choices=[('PEN', 'pending'), ('CON', 'confirmed'), ('CANCEL', 'cancelled'), ('COM', 'completed')], default='PEN', max_length=10)),
                ('doctor', models.ForeignKey(limit_choices_to={'title': ['DR', 'CT']}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.employees')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosage', models.IntegerField()),
                ('medical_staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.employees')),
                ('medications', models.ManyToManyField(to='myapp.medication')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PEN', 'pending'), ('CON', 'confirmed'), ('CANCEL', 'cancelled'), ('COM', 'completed')], default='PEN', max_length=10)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('total_cost', models.FloatField()),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.prescription')),
            ],
        ),
    ]
