# Generated by Django 5.1 on 2024-09-22 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_temporarytoken_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temporarytoken',
            name='user',
        ),
    ]
