# Generated by Django 5.1 on 2024-09-08 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patientportal', '0004_alter_userprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='patient',
        ),
    ]
